=== SIPfoundry/legacy-sipxecs/sipXconfig/web/src/org/sipfoundry/sipxconfig/site/spring-beans.dtd
<!ELEMENT beans (
	description?,
	(import | alias | bean)*
)>
 
<!ATTLIST beans default-lazy-init (true | false) "false">
<!ATTLIST beans default-autowire (no | byName | byType | constructor | autodetect) "no">
<!ATTLIST beans default-dependency-check (none | objects | simple | all) "none">
<!ATTLIST beans default-init-method CDATA #IMPLIED>
<!ATTLIST beans default-destroy-method CDATA #IMPLIED>
 
<!ELEMENT description (#PCDATA)>
 
<!ELEMENT import EMPTY>
 
<!ATTLIST import resource CDATA #REQUIRED>
 
<!ELEMENT alias EMPTY>
 
<!ATTLIST alias name CDATA #REQUIRED>
 
<!ATTLIST alias alias CDATA #REQUIRED>
 
<!ELEMENT bean (
	description?,
	(constructor-arg | property | lookup-method | replaced-method)*
)>
 
<!ATTLIST bean id ID #IMPLIED>
 
<!ATTLIST bean name CDATA #IMPLIED>
 
<!ATTLIST bean class CDATA #IMPLIED>
 
<!ATTLIST bean parent CDATA #IMPLIED>
 
<!ATTLIST bean abstract (true | false) #IMPLIED>
 
<!ATTLIST bean singleton (true | false) #IMPLIED>
 
<!ATTLIST bean lazy-init (true | false | default) "default">
 
<!ATTLIST bean autowire (no | byName | byType | constructor | autodetect | default) "default">
 
<!ATTLIST bean dependency-check (none | objects | simple | all | default) "default">
 
<!ATTLIST bean depends-on CDATA #IMPLIED>
 
<!ATTLIST bean init-method CDATA #IMPLIED>
 
<!ATTLIST bean destroy-method CDATA #IMPLIED>
 
<!ATTLIST bean factory-method CDATA #IMPLIED>
 
<!ATTLIST bean factory-bean CDATA #IMPLIED>
 
<!ELEMENT constructor-arg (
	description?,
	(bean | ref | idref | value | null | list | set | map | props)?
)>
 
<!ATTLIST constructor-arg index CDATA #IMPLIED>
 
<!ATTLIST constructor-arg type CDATA #IMPLIED>
 
<!ATTLIST constructor-arg ref CDATA #IMPLIED>
 
<!ATTLIST constructor-arg value CDATA #IMPLIED>
 
<!ELEMENT property (
	description?,
	(bean | ref | idref | value | null | list | set | map | props)?
)>
 
<!ATTLIST property name CDATA #REQUIRED>
 
<!ATTLIST property ref CDATA #IMPLIED>
 
<!ATTLIST property value CDATA #IMPLIED>
 
<!ELEMENT lookup-method EMPTY>
 
<!ATTLIST lookup-method name CDATA #IMPLIED>
 
<!ATTLIST lookup-method bean CDATA #IMPLIED>
 
<!ELEMENT replaced-method (
	(arg-type)*
)>
 
<!ATTLIST replaced-method name CDATA #IMPLIED>
 
<!ATTLIST replaced-method replacer CDATA #IMPLIED>
 
<!ELEMENT arg-type (#PCDATA)>
 
<!ATTLIST arg-type match CDATA #IMPLIED>
 
<!ELEMENT ref EMPTY>
 
<!ATTLIST ref bean CDATA #IMPLIED>
<!ATTLIST ref local IDREF #IMPLIED>
<!ATTLIST ref parent CDATA #IMPLIED>
 
<!ELEMENT idref EMPTY>
 
<!ATTLIST idref bean CDATA #IMPLIED>
<!ATTLIST idref local IDREF #IMPLIED>
 
<!ELEMENT value (#PCDATA)>
 
<!ATTLIST value type CDATA #IMPLIED>
 
<!ELEMENT null (#PCDATA)>
 
<!ELEMENT list (
	(bean | ref | idref | value | null | list | set | map | props)*
)>
 
<!ELEMENT set (
	(bean | ref | idref | value | null | list | set | map | props)*
)>
 
<!ELEMENT map (
	(entry)*
)>
 
<!ELEMENT entry (
  key?,
	(bean | ref | idref | value | null | list | set | map | props)?
)>
 
<!ATTLIST entry key CDATA #IMPLIED>
 
<!ATTLIST entry key-ref CDATA #IMPLIED>
 
<!ATTLIST entry value CDATA #IMPLIED>
 
<!ATTLIST entry value-ref CDATA #IMPLIED>
 
<!ELEMENT key (
	(bean | ref | idref | value | null | list | set | map | props)
)>
 
<!ELEMENT props (
	(prop)*
)>
 
<!ELEMENT prop (#PCDATA)>
 
<!ATTLIST prop key CDATA #REQUIRED>

=== SIPfoundry/legacy-sipxecs/sipXconfig/neoconf/src/org/sipfoundry/sipxconfig/device/device.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd" >
<beans>
  <!-- most phone defaults properties is set in sipxconfig.properties.in -->
  <bean id="phoneDefaults" class="org.sipfoundry.sipxconfig.device.DeviceDefaults">
    <property name="dialPlanContext" ref="dialPlanContext" />
    <property name="domainManager" ref="domainManager" />
    <property name="sipxServer" ref="sipxServer" />
    <property name="serviceManager" ref="serviceManager" />
    <property name="logDirectory" value="${sysdir.log}"></property>
  </bean>


  <bean id="tftpProfileLocation" class="org.sipfoundry.sipxconfig.device.FileSystemProfileLocation">
    <property name="parentDir">
      <value>${sysdir.phone}/profile/tftproot</value>
    </property>
  </bean>

  <bean id="httpProfileLocation" class="org.sipfoundry.sipxconfig.device.FileSystemProfileLocation">
    <property name="parentDir">
      <!-- 
        - this is directory for a preferred place for serving 
        - phone configuration profiles for http access
        -    http://host:8090/phone/profile/docroot/, 
      -->
      <value>${sysdir.phone}/profile/docroot</value>
    </property>
  </bean>

  <bean id="velocityProfileGenerator" class="org.sipfoundry.sipxconfig.device.VelocityProfileGenerator">
    <property name="templateRoot" value="${sysdir.etc}" />
    <property name="velocityEngine" ref="velocityEngine" />
  </bean>
  
  <bean id="restartExecutorService" class="org.springframework.scheduling.concurrent.ScheduledExecutorFactoryBean">
  </bean>
</beans>

=== SIPfoundry/legacy-sipxecs/sipXconfig/neoconf/etc/region_br/dialrules.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>

  <!--  The default dial plan for Brazil  -->

  <!-- properties: voiceMail, voiceMailPrefix -->
  <bean id="br.voicemailRule" parent="defaultInternalRule" singleton="false">
    <property name="name" value="Correio de voz" />
    <property name="description" value="Plano de discagem padrão para correio de voz" />
    <property name="voiceMail" value="101" />
    <property name="voiceMailPrefix" value="8" />
  </bean>

  <!-- properties: extension, attendantAliases -->
  <bean id="br.attendantRule" parent="defaultAttendantRule" singleton="false">
    <property name="name" value="Atendente automático" />
    <property name="description" value="Plano de discagem padrão para atendente automático" />
    <property name="extension" value="100" />
    <property name="attendantAliases" value="operator 0" />
  </bean>

  <bean id="br.fireEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Incêndio" />
    <property name="description" value="Emergência - incêndio" />
    <property name="emergencyNumber" value="193" />
  </bean>
  <bean id="br.ambulanceEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Ambulância" />
    <property name="description" value="Emergência - médica" />
    <property name="emergencyNumber" value="192" />
  </bean>
  <bean id="br.policeEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Polícia" />
    <property name="description" value="Emergência - Polícia" />
    <property name="emergencyNumber" value="190" />
  </bean>

  <bean id="br.localRule" parent="defaultLocalRule" singleton="false">
    <property name="name" value="Local" />
    <property name="description" value="Plano de discagem local" />
    <property name="pstnPrefix" value="" />
    <property name="externalLen" value="8" />
    <property name="areaCodes" value="2,3,4,5,6,7,8,9" />
  </bean>
  <bean id="br.localCollectRule" parent="br.localRule" singleton="false">
    <property name="name" value="Local a cobrar" />
    <property name="description" value="Plano de discagem de chamada local a cobrar" />
    <property name="externalLen" value="12" />
    <property name="areaCodes" value="9090" />
  </bean>

  <!-- properties for all long distance rules:  pstnPrefixOptional, pstnPrefix,
    longDistancePrefixOptional, longDistancePrefix, externalLen, permissionName -->
  <bean id="br.longDistanceRule" parent="defaultLongDistanceRule" singleton="false">
    <property name="name" value="Longa Distância" />
    <property name="description" value="Plano de discagem de longa distância" />
    <property name="areaCodes" value="11,12,13,14,15,16,17,18,19,21,22,24,27,28,31,32,33,34,35,37,38,41,42,43,44,45,46,47,48,49,51,53,54,55,61,62,63,64,65,66,67,68,69,71,73,74,75,77,79,81,82,83,84,85,86,87,88,89,91,92,93,94,95,96,97,98,99" />
    <property name="longDistancePrefix" value="0xx" />
    <property name="externalLen" value="10" />
    <property name="permissionName" value="LongDistanceDialing" />
  </bean>
  <bean id="br.longDistanceCollectRule" parent="br.longDistanceRule" singleton="false">
    <property name="name" value="Longa Distância a cobrar" />
    <property name="description" value="Plano de discagem de chamada a cobrar de longa distância" />
    <property name="longDistancePrefix" value="90xx" />
  </bean>
  <bean id="br.locationIndependentRule" parent="br.longDistanceRule" singleton="false">
    <property name="name" value="Independente do local" />
    <property name="description" value="Números de telefone de longa distância independente do local" />
    <property name="longDistancePrefix" value="0" />
    <property name="areaCodes" value="300" />
  </bean>
  <bean id="br.premiumRateRule" parent="br.longDistanceRule" singleton="false">
    <property name="name" value="Tarifa Especial" />
    <property name="description" value="Serviços com tarifa especial" />
    <property name="longDistancePrefix" value="0" />
    <property name="areaCodes" value="500,900" />
    <property name="permissionName" value="900Dialing" />
  </bean>
  <bean id="br.tollFreeRule" parent="defaultTollFreeRule" singleton="false">
    <property name="name" value="Ligue grátis" />
    <property name="description" value="Discagem gratuita" />
    <property name="longDistancePrefix" value="0" />
    <property name="areaCodes" value="800" />
    <property name="permissionName" value="TollFree" />
  </bean>
  <bean id="br.internationalRule" parent="defaultInternationalRule" singleton="false">
    <property name="name" value="Internacional" />
    <property name="description" value="Discagem internacional" />
    <property name="longDistancePrefix" value="00xx" />
    <property name="externalLen" value="-1" />
    <property name="areaCodes" value="" />
    <property name="permissionName" value="InternationalDialing" />
  </bean>

  <!-- defaultDialPlan defines the "factory default" structure of your valid plan -->
  <!-- this is the list of rules that admin will see after installation and after reverting to default -->
  <bean id="br.dialPlan" parent="defaultDialPlan" singleton="false">
    <property name="rules">
      <list>
        <ref bean="br.voicemailRule" />
        <ref bean="br.attendantRule" />
        <ref bean="br.fireEmergencyRule" />
        <ref bean="br.ambulanceEmergencyRule" />
        <ref bean="br.policeEmergencyRule" />
        <ref bean="br.localRule" />
        <ref bean="br.localCollectRule" />
        <ref bean="br.longDistanceRule" />
        <ref bean="br.longDistanceCollectRule" />
        <ref bean="br.locationIndependentRule" />
        <ref bean="br.premiumRateRule" />
        <ref bean="br.tollFreeRule" />
        <ref bean="br.internationalRule" />
      </list>
    </property>
  </bean>

</beans>

=== SIPfoundry/legacy-sipxecs/sipXconfig/neoconf/etc/region_pl/dialrules.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>

  <!--  proposal of the default dial plan for Poland  -->
  <!--  based on information in UKE (Urzad komunikacii elektronicznej) -->
  <!--  it's using 9 as optional PSTN prefix but it can be changed -->
  <!--  some classes added to make it simpler to allow acces to infolines and similar -->
  <!--  classes added for national emergency lines -->
  <!--  Redefined longdistance class to the 49 long distance prefixes available to exclude access to special numbers -->
  <!--  which could have been omitted by accident :) -->

  <!-- properties: voiceMail, voiceMailPrefix -->
  <bean id="pl.internalRule" parent="defaultInternalRule" singleton="false">
    <property name="voiceMail" value="101" />
    <property name="voiceMailPrefix" value="8" />
  </bean>

  <!-- properties: extension, attendantAliases -->
  <bean id="pl.attendantRule" parent="defaultAttendantRule" singleton="false">
    <property name="extension" value="100" />
    <property name="attendantAliases" value="operator 0" />
  </bean>

  <!-- properties: optionalPrefix, emergencyNumber -->
  <bean id="pl.emergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Police" />
    <property name="emergencyNumber" value="997" />
  </bean>
  <bean id="pl.fireEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Fire department" />
    <property name="emergencyNumber" value="998" />
  </bean>
  <bean id="pl.ambulanceEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Ambulance" />
    <property name="emergencyNumber" value="999" />
  </bean>
  <bean id="pl.centralEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="CountrywideEmergency" />
    <property name="emergencyNumber" value="112" />
  </bean>
  <bean id="pl.electricityEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Electricity" />
    <property name="emergencyNumber" value="991" />
  </bean>
  <bean id="pl.gasEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Gas" />
    <property name="emergencyNumber" value="992" />
  </bean>
  <bean id="pl.heatingEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Heating" />
    <property name="emergencyNumber" value="993" />
  </bean>
  <bean id="pl.waterEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Water" />
    <property name="emergencyNumber" value="994" />
  </bean>
  <bean id="pl.cityguardsEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="CityGuards" />
    <property name="emergencyNumber" value="986" />
  </bean>

  <!-- properties for all long distance rules:  pstnPrefixOptional, pstnPrefix,
    longDistancePrefixOptional, longDistancePrefix, externalLen, permissionName -->
  <!-- if you are located outside warsaw, please add 22 to the list of area codes here and replace the 022 in local with your local area code -->
  <bean id="pl.longDistanceRule" parent="defaultLongDistanceRule" singleton="false">
    <property name="pstnPrefixOptional" value="false" />
    <property name="pstnPrefix" value="9" />
    <property name="longDistancePrefixOptional" value="false" />
    <property name="longDistancePrefix" value="0" />
    <property name="externalLen" value="9" />
    <property name="areaCodes"
      value="75,76,74,71,52,56,54,83,82,81,84,95,68,42,44,43,12,18,14,23,29,24,48,25,77,13,16,17,15,85,86,87,58,59,33,34,32,41,55,89,62,63,65,67,61,94,91" />
    <property name="permissionName" value="LongDistanceDialing" />
  </bean>

  <bean id="pl.tollFreeRule" parent="defaultTollFreeRule" singleton="false">
    <property name="name" value="Toll free" />
    <property name="description" value="Toll free dialing" />
    <property name="areaCodes" value="800,806,808" />
    <property name="permissionName" value="TollFree" />
  </bean>

  <bean id="pl.restrictedRule" parent="defaultRestrictedRule" singleton="false">
    <property name="name" value="Restricted" />
    <property name="description" value="Restricted dialing" />
    <property name="areaCodes" value="300, 400, 700, 900, 901, 906" />
    <property name="permissionName" value="900Dialing" />
  </bean>

  <bean id="pl.infolineRule" parent="pl.longDistanceRule" singleton="false">
    <!--  since there are a lot of places where infolines, like the number information etc.
      have to be permitted separately, here a class for them, for now restricted to 900Dialing permissions -->
    <property name="name" value="Infolines" />
    <property name="description" value="Infolines, restricted dialing" />
    <property name="longDistancePrefix" value="" />
    <property name="areaCodes" value="118" />
    <property name="externalLen" value="-1" />
    <property name="permissionName" value="900Dialing" />
  </bean>

  <bean id="pl.mobileRule" parent="pl.longDistanceRule" singleton="false">
    <property name="name" value="Mobile" />
    <property name="description" value="Mobile numbers" />
    <property name="areaCodes" value="50, 51, 60, 66, 69, 72, 78, 79, 88" />
    <property name="permissionName" value="Mobile" />
  </bean>

  <bean id="pl.internationalRule" parent="defaultInternationalRule" singleton="false">
    <property name="name" value="International" />
    <property name="description" value="International dialing" />
    <property name="longDistancePrefix" value="00" />
    <property name="areaCodes" value="" />
    <property name="externalLen" value="-1" />
    <property name="permissionName" value="InternationalDialing" />
  </bean>

  <!-- Needs to be adjusted by user to his arecode since that is dialed as longdistance but prices differ vastly ..
    This example is for Warsaw, for a different City, replace the area code with the local one  -->
  <bean id="pl.localRule" parent="defaultLocalRule" singleton="false">
    <property name="name" value="Local" />
    <property name="description" value="Local dialing" />
    <property name="areaCodes" value="22" />
    <property name="permissionName" value="LocalDialing" />
  </bean>

  <!-- defaultDialPlan defines the "factory default" structure of your valid plan -->
  <!-- this is the list of rules that admin will see after installation and after reverting to default -->
  <bean id="pl.dialPlan" parent="defaultDialPlan" singleton="false">
    <property name="rules">
      <list>
        <ref bean="pl.emergencyRule" />
        <ref bean="pl.fireEmergencyRule" />
        <ref bean="pl.ambulanceEmergencyRule" />
        <ref bean="pl.centralEmergencyRule" />
        <ref bean="pl.electricityEmergencyRule" />
        <ref bean="pl.gasEmergencyRule" />
        <ref bean="pl.heatingEmergencyRule" />
        <ref bean="pl.waterEmergencyRule" />
        <ref bean="pl.cityguardsEmergencyRule" />
        <ref bean="pl.localRule" />
        <ref bean="pl.mobileRule" />
        <ref bean="pl.infolineRule" />
        <ref bean="pl.restrictedRule" />
        <ref bean="pl.tollFreeRule" />
        <ref bean="pl.longDistanceRule" />
        <ref bean="pl.internationalRule" />
        <ref bean="pl.attendantRule" />
        <ref bean="pl.internalRule" />
      </list>
    </property>
  </bean>

</beans>

=== SIPfoundry/legacy-sipxecs/sipXconfig/neoconf/etc/region_ch/dialrules.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>

  <!--  proposal of the default dial plan for Switzerland  -->
  <!--  based on information in  -->
  <!-- it's using 9 as optional PSTN prefix but it can be changed -->

  <!-- properties: voiceMail, voiceMailPrefix -->
  <bean id="ch.internalRule" parent="defaultInternalRule" singleton="false">
    <property name="name" value="Anrufbeantworter" />
    <property name="description" value="Wählplan für den Anrufbeantworter" />
    <property name="voiceMail" value="101" />
    <property name="voiceMailPrefix" value="8" />
  </bean>

  <!-- properties: extension, attendantAliases -->
  <bean id="ch.attendantRule" parent="defaultAttendantRule" singleton="false">
    <property name="name" value="Automatisches Antwortsystem" />
    <property name="description" value="Wählplan für das automatische Antwortsystem" />
    <property name="extension" value="100" />
    <property name="attendantAliases" value="operator 0" />
  </bean>

  <!-- properties: optionalPrefix, emergencyNumber -->
  <bean id="ch.emergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Notfallnummer" />
    <property name="description" value="Notfallnummer für die Schweiz" />
    <property name="emergencyNumber" value="112" />
  </bean>
  <bean id="ch.policeEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Polizei" />
    <property name="description" value="Notfallnummer für die Polizei" />
    <property name="emergencyNumber" value="117" />
  </bean>
  <bean id="ch.fireEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Feuerwache" />
    <property name="description" value="Notfallnummer für die Feuerwache" />
    <property name="emergencyNumber" value="118" />
  </bean>
  <bean id="ch.ambulanceEmergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Ambulanz" />
    <property name="description" value="Notfallnummer für den Rettungswagen" />
    <property name="emergencyNumber" value="144" />
  </bean>

  <!-- properties for all long distance rules:  pstnPrefixOptional, pstnPrefix,
    longDistancePrefixOptional, longDistancePrefix, externalLen, permissionName -->
  <bean id="ch.longDistanceRule" parent="defaultLongDistanceRule" singleton="false">
    <property name="name" value="Ferngespräche" />
    <property name="description" value="Wählplan für Ferngespräche" />
    <property name="pstnPrefixOptional" value="false" />
    <property name="pstnPrefix" value="9" />
    <property name="longDistancePrefixOptional" value="false" />
    <property name="longDistancePrefix" value="0" />
    <property name="externalLen" value="-1" />
    <property name="permissionName" value="LongDistanceDialing" />
  </bean>

  <bean id="ch.tollFreeRule" parent="defaultTollFreeRule" singleton="false">
    <property name="name" value="Gratisnummern" />
    <property name="description" value="Wählen von Gratisnummern" />
    <property name="areaCodes" value="800" />
    <property name="externalLen" value="9" />
    <property name="permissionName" value="TollFree" />
  </bean>

  <bean id="ch.restrictedRule" parent="defaultRestrictedRule" singleton="false">
    <property name="name" value="Mehrwertdienste" />
    <property name="description" value="Zuschlagspflichtige Nummern" />
    <property name="areaCodes" value="900, 901, 906" />
    <property name="externalLen" value="9" />
    <property name="permissionName" value="900Dialing" />
  </bean>

  <bean id="ch.mobileRule" parent="ch.longDistanceRule" singleton="false">
    <property name="name" value="Mobiltelefone" />
    <property name="description" value="Wählen von Mobilteilnehmern" />
    <property name="areaCodes" value="76, 77, 78, 79" />
    <property name="externalLen" value="9" />
    <property name="permissionName" value="Mobile" />
  </bean>

  <bean id="ch.internationalRule" parent="defaultInternationalRule" singleton="false">
    <property name="name" value="International" />
    <property name="description" value="Wählen von internationalen Nummern" />
    <property name="longDistancePrefix" value="00" />
    <property name="externalLen" value="-1" />
    <property name="permissionName" value="InternationalDialing" />
  </bean>

  <bean id="ch.infolineRule" parent="ch.longDistanceRule" singleton="false">
    <property name="name" value="Informationsdienste" />
    <property name="description" value="Telefoninformationsdienste, welche keine Vorwahl benötigen" />
    <property name="areaCodes" value="16, 18" />
    <property name="longDistancePrefix" value="" />
    <property name="externalLen" value="-1" />
    <property name="permissionName" value="900Dialing" />
  </bean>

  <!-- defaultDialPlan defines the "factory default" structure of your valid plan -->
  <!-- this is the list of rules that admin will see after installation and after reverting to default -->
  <bean id="ch.dialPlan" parent="defaultDialPlan" singleton="false">
    <property name="rules">
      <list>
        <ref bean="ch.emergencyRule" />
        <ref bean="ch.policeEmergencyRule" />
        <ref bean="ch.fireEmergencyRule" />
        <ref bean="ch.ambulanceEmergencyRule" />
        <ref bean="ch.mobileRule" />
        <ref bean="ch.restrictedRule" />
        <ref bean="ch.tollFreeRule" />
        <ref bean="ch.longDistanceRule" />
        <ref bean="ch.internationalRule" />
        <ref bean="ch.infolineRule" />
        <ref bean="ch.attendantRule" />
        <ref bean="ch.internalRule" />
      </list>
    </property>
  </bean>

</beans>

=== SIPfoundry/legacy-sipxecs/sipXconfig/plugins/mitel/src/org/sipfoundry/sipxconfig/phone/mitel/mitel-models.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN"
  "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>
  <!-- models -->
  <bean id="mitel5224" parent="abstractPhoneModel">
    <property name="label" value="Mitel 5224" />
    <property name="beanId" value="mitel" />
    <property name="maxLineCount" value="1" />
    <property name="profileTemplate" value="mitel/mn.txt.vm" />
	<property name="vendor" value="MITEL"/>
  </bean>
  <!-- implementation -->
  <bean id="mitel" class="org.sipfoundry.sipxconfig.phone.mitel.MitelPhone" singleton="false" parent="abstractPhone">
  </bean>
</beans>

=== SIPfoundry/legacy-sipxecs/sipXconfig/plugins/lg-nortel/src/org/sipfoundry/sipxconfig/phone/lg_nortel/lg-nortel-models.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" 
  "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>
  <!-- models -->
  <bean id="lip6804" class="org.sipfoundry.sipxconfig.phone.lg_nortel.LgNortelModel">
    <property name="label" value="LIP-6804" />
    <property name="maxLineCount" value="4" />
  </bean>
  <bean id="lip6812" class="org.sipfoundry.sipxconfig.phone.lg_nortel.LgNortelModel">
    <property name="label" value="LIP-6812" />
    <property name="maxLineCount" value="11" />
  </bean>
  <bean id="lip6830" class="org.sipfoundry.sipxconfig.phone.lg_nortel.LgNortelModel">
    <property name="label" value="LIP-6830" />
    <property name="maxLineCount" value="24" />
  </bean>
  <!-- implementation -->
  <bean id="lg-nortel" class="org.sipfoundry.sipxconfig.phone.lg_nortel.LgNortelPhone"
    singleton="false" parent="abstractPhone">
  </bean>
  <bean id="lg-nortelFirmware" class="org.sipfoundry.sipxconfig.upload.UploadSpecification">
    <property name="beanId" value="zipUpload"/>
    <property name="modelFilePath" value="lg-nortel/upload.xml"/>
    <property name="label" value="LG-Nortel LIP-68xx" />
  </bean>      
</beans>

=== SIPfoundry/legacy-sipxecs/sipXconfig/neoconf/src/org/sipfoundry/sipxconfig/admin/configdiag/configdiag.beans.xml
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN"
	"http://www.springframework.org/dtd/spring-beans.dtd">
<beans>
  <bean id="configurationDiagnosticContext"
    class="org.sipfoundry.sipxconfig.admin.configdiag.ConfigurationDiagnosticContextImpl">
    <property name="descriptorPath">
      <value>${sysdir.etc}/test.d</value>
    </property>
    <property name="externalCommandContext" ref="commandContext" />
    <property name="preflightInstallerLocation" value="${sysdir.share}/preflight/preflight_installer.exe" />
  </bean>

  <bean id="commandContext" class="org.sipfoundry.sipxconfig.admin.configdiag.DefaultExternalCommandContext">
    <property name="binDirectory">
      <value>${sysdir.bin}</value>
    </property>
    <property name="locationsManager" ref="locationsManager" />
    <property name="domainManager" ref="domainManager" />
  </bean>
</beans>

=== SIPfoundry/legacy-sipxecs/sipXconfig/neoconf/src/org/sipfoundry/sipxconfig/gateway/acme/acme-models.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN"
	"http://www.springframework.org/dtd/spring-beans.dtd">
<beans>
  <!-- This is just an example of how to register new gateway -->
  <bean id="acmeGatewayStandard" parent="abstractGatewayModel">
    <property name="beanId" value="gwAcme" />
    <property name="label" value="Acme 1000" />
    <property name="profileTemplate" value="acme/acme-gateway.vm" />
    <property name="modelDir" value="acme" />
	<property name="vendor" value="acme" />
  </bean>

  <bean id="gwAcme" class="org.sipfoundry.sipxconfig.gateway.acme.AcmeGateway" singleton="false" parent="gwGeneric">
  </bean>
</beans>
