=== SIPfoundry/legacy-sipxecs/sipXconfig/web/src/org/sipfoundry/sipxconfig/site/spring-beans.dtd
<!ELEMENT beans (
	description?,
	(import | alias | bean)*
)>
 
<!ATTLIST beans default-lazy-init (true | false) "false">
<!ATTLIST beans default-autowire (no | byName | byType | constructor | autodetect) "no">
<!ATTLIST beans default-dependency-check (none | objects | simple | all) "none">
<!ATTLIST beans default-init-method CDATA #IMPLIED>
<!ATTLIST beans default-destroy-method CDATA #IMPLIED>
 
<!ELEMENT description (#PCDATA)>
 
<!ELEMENT import EMPTY>
 
<!ATTLIST import resource CDATA #REQUIRED>
 
<!ELEMENT alias EMPTY>
 
<!ATTLIST alias name CDATA #REQUIRED>
 
<!ATTLIST alias alias CDATA #REQUIRED>
 
<!ELEMENT bean (
	description?,
	(constructor-arg | property | lookup-method | replaced-method)*
)>
 
<!ATTLIST bean id ID #IMPLIED>
 
<!ATTLIST bean name CDATA #IMPLIED>
 
<!ATTLIST bean class CDATA #IMPLIED>
 
<!ATTLIST bean parent CDATA #IMPLIED>
 
<!ATTLIST bean abstract (true | false) #IMPLIED>
 
<!ATTLIST bean singleton (true | false) #IMPLIED>
 
<!ATTLIST bean lazy-init (true | false | default) "default">
 
<!ATTLIST bean autowire (no | byName | byType | constructor | autodetect | default) "default">
 
<!ATTLIST bean dependency-check (none | objects | simple | all | default) "default">
 
<!ATTLIST bean depends-on CDATA #IMPLIED>
 
<!ATTLIST bean init-method CDATA #IMPLIED>
 
<!ATTLIST bean destroy-method CDATA #IMPLIED>
 
<!ATTLIST bean factory-method CDATA #IMPLIED>
 
<!ATTLIST bean factory-bean CDATA #IMPLIED>
 
<!ELEMENT constructor-arg (
	description?,
	(bean | ref | idref | value | null | list | set | map | props)?
)>
 
<!ATTLIST constructor-arg index CDATA #IMPLIED>
 
<!ATTLIST constructor-arg type CDATA #IMPLIED>
 
<!ATTLIST constructor-arg ref CDATA #IMPLIED>
 
<!ATTLIST constructor-arg value CDATA #IMPLIED>
 
<!ELEMENT property (
	description?,
	(bean | ref | idref | value | null | list | set | map | props)?
)>
 
<!ATTLIST property name CDATA #REQUIRED>
 
<!ATTLIST property ref CDATA #IMPLIED>
 
<!ATTLIST property value CDATA #IMPLIED>
 
<!ELEMENT lookup-method EMPTY>
 
<!ATTLIST lookup-method name CDATA #IMPLIED>
 
<!ATTLIST lookup-method bean CDATA #IMPLIED>
 
<!ELEMENT replaced-method (
	(arg-type)*
)>
 
<!ATTLIST replaced-method name CDATA #IMPLIED>
 
<!ATTLIST replaced-method replacer CDATA #IMPLIED>
 
<!ELEMENT arg-type (#PCDATA)>
 
<!ATTLIST arg-type match CDATA #IMPLIED>
 
<!ELEMENT ref EMPTY>
 
<!ATTLIST ref bean CDATA #IMPLIED>
<!ATTLIST ref local IDREF #IMPLIED>
<!ATTLIST ref parent CDATA #IMPLIED>
 
<!ELEMENT idref EMPTY>
 
<!ATTLIST idref bean CDATA #IMPLIED>
<!ATTLIST idref local IDREF #IMPLIED>
 
<!ELEMENT value (#PCDATA)>
 
<!ATTLIST value type CDATA #IMPLIED>
 
<!ELEMENT null (#PCDATA)>
 
<!ELEMENT list (
	(bean | ref | idref | value | null | list | set | map | props)*
)>
 
<!ELEMENT set (
	(bean | ref | idref | value | null | list | set | map | props)*
)>
 
<!ELEMENT map (
	(entry)*
)>
 
<!ELEMENT entry (
  key?,
	(bean | ref | idref | value | null | list | set | map | props)?
)>
 
<!ATTLIST entry key CDATA #IMPLIED>
 
<!ATTLIST entry key-ref CDATA #IMPLIED>
 
<!ATTLIST entry value CDATA #IMPLIED>
 
<!ATTLIST entry value-ref CDATA #IMPLIED>
 
<!ELEMENT key (
	(bean | ref | idref | value | null | list | set | map | props)
)>
 
<!ELEMENT props (
	(prop)*
)>
 
<!ELEMENT prop (#PCDATA)>
 
<!ATTLIST prop key CDATA #REQUIRED>

=== SIPfoundry/legacy-sipxecs/sipXconfig/plugins/nortel/src/org/sipfoundry/sipxconfig/phone/nortel/nortel-models.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN"
  "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>
  <bean id="nortelModel" abstract="true" class="org.sipfoundry.sipxconfig.phone.nortel.NortelPhoneModel"
  	parent="abstractPhoneModel">
    <property name="beanId" value="nortel" />
    <property name="label" value="Nortel IP Phone 1120/40" />
    <property name="maxLineCount" value="24" />
    <property name="profileTemplate" value="nortel/mac.cfg.vm" />
    <property name="restartSupported" value="true" />
  </bean>

  <!-- models -->
  <bean id="nortel11xx" parent="nortelModel">
    <property name="label" value="Nortel IP Phone 1120/40" />
  </bean>

  <!-- implementation -->
  <bean id="nortel" class="org.sipfoundry.sipxconfig.phone.nortel.NortelPhone" singleton="false"
    parent="abstractPhone">
     <property name="coreContext" ref="coreContext" />
  </bean>

  <bean id="nortelFirmware" class="org.sipfoundry.sipxconfig.upload.UploadSpecification">
    <property name="beanId" value="upload" />
    <property name="modelFilePath" value="nortel/upload.xml" />
    <property name="label" value="Nortel IP Phone 1120/40" />
  </bean>
</beans>

=== SIPfoundry/legacy-sipxecs/sipXconfig/plugins/ciscospa/src/org/sipfoundry/sipxconfig/phone/Ciscospa/linksys-models.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN"
  "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>
  <bean id="CiscospaModel" class="org.sipfoundry.sipxconfig.phone.linksys.CiscospaModel" parent="abstractPhoneModel"
    abstract="true">
    <property name="restartSupported" value="true" />
  </bean>

  <bean id="linksysPhoneStandard" abstract="true" parent="LinksysModel">
    <property name="beanId" value="CiscospaPhone" />
    <property name="modelDir" value="Ciscospa" />
    <property name="profileTemplate" value="linksys/config.vm" />
  </bean>

  <bean id="SPA501G" parent="linksysPhoneStandard">
    <property name="label" value="Cisco SPA501G" />
    <property name="maxLineCount" value="1" />
    <property name="psn" value="501G" />
  </bean>
  <bean id="SPA502G" parent="linksysPhoneStandard">
    <property name="label" value="Cisco SPA502G" />
    <property name="maxLineCount" value="2" />
    <property name="psn" value="502G" />
  </bean>
  <bean id="SPA504G" parent="linksysPhoneStandard">
    <property name="label" value="Cisco SPA504G" />
    <property name="maxLineCount" value="4" />
    <property name="psn" value="504G" />

  </bean>
  <bean id="SPA508G" parent="linksysPhoneStandard">
    <property name="label" value="Cisco SPA508G" />
    <property name="maxLineCount" value="8" />
    <property name="psn" value="508G" />
  </bean>
  <bean id="SPA509G" parent="linksysPhoneStandard">
    <property name="label" value="Cisco SPA509G" />
    <property name="maxLineCount" value="12" />
    <property name="psn" value="509G" />
  </bean>
  <bean id="SPA525G" parent="linksysPhoneStandard">
    <property name="label" value="Cisco SPA525G" />
    <property name="maxLineCount" value="12" />
    <property name="psn" value="525G" />
  </bean>
  
  <bean id="CiscospaPhone" class="org.sipfoundry.sipxconfig.phone.linksys.CiscospaPhone" singleton="false"
    parent="abstractPhone">
  </bean> 
</beans>

=== SIPfoundry/legacy-sipxecs/sipXconfig/plugins/snom/src/org/sipfoundry/sipxconfig/phone/snom/snom-models.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN"
  "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>
  <bean id="snomModel" abstract="true" parent="abstractPhoneModel">
    <property name="beanId" value="snom" />
    <property name="defaultProfileLocation" ref="httpProfileLocation" />
    <property name="profileTemplate" value="snom/snom.vm" />
    <property name="vendor" value="SNOM" />
    <property name="restartSupported" value="true" />
  </bean>

  <bean id="snom300" parent="snomModel">
    <property name="label" value="Snom 300" />
    <property name="maxLineCount" value="4" />
    <property name="supportedFeatures">
      <set>
        <value>intercom</value>
      </set>
    </property>
  </bean>
  <bean id="snom320" parent="snomModel">
    <property name="label" value="Snom 320" />
    <property name="maxLineCount" value="12" />
    <property name="supportedFeatures">
      <set>
        <value>intercom</value>
      </set>
    </property>
  </bean>
  <bean id="snom360" parent="snomModel">
    <property name="label" value="Snom 360" />
    <property name="maxLineCount" value="12" />
    <property name="supportedFeatures">
      <set>
        <value>intercom</value>
        <value>blf</value>
      </set>
    </property>
  </bean>
  <bean id="snom370" parent="snomModel">
    <property name="label" value="Snom 370" />
    <property name="maxLineCount" value="12" />
    <property name="supportedFeatures">
      <set>
        <value>intercom</value>
        <value>blf</value>
      </set>
    </property>
  </bean>
  <bean id="snom" class="org.sipfoundry.sipxconfig.phone.snom.SnomPhone" singleton="false" parent="abstractPhone">
    <property name="speedDialManager" ref="speedDialManager" />
  </bean>
</beans>

=== SIPfoundry/legacy-sipxecs/sipXconfig/neoconf/etc/region_uk/dialrules.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>

  <!--  The default dial plan for the United Kingdom  -->

  <!-- properties: voiceMail, voiceMailPrefix -->
  <bean id="uk.voicemailRule" parent="defaultInternalRule" singleton="false">
    <property name="name" value="Voice mail" />
    <property name="description" value="Default voice mail dialing plan" />
    <property name="voiceMail" value="101" />
    <property name="voiceMailPrefix" value="8" />
  </bean>

  <!-- properties: extension, attendantAliases -->
  <bean id="uk.attendantRule" parent="defaultAttendantRule" singleton="false">
    <property name="name" value="Auto attendant" />
    <property name="description" value="Default auto attendant dialing plan" />
    <property name="extension" value="100" />
    <property name="attendantAliases" value="operator 0" />
  </bean>

  <!-- properties: optionalPrefix, emergencyNumber -->
  <bean id="uk.emergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Emergency" />
    <property name="description" value="Emergency - central telephone number" />
    <property name="optionalPrefix" value="9" />
    <property name="emergencyNumber" value="112" />
  </bean>
  <bean id="uk.oldEmergencyRule" parent="uk.emergencyRule" singleton="false">
    <property name="name" value="Old Emergency" />
    <property name="description" value="Emergency - old central telephone number" />
    <property name="emergencyNumber" value="999" />
  </bean>
  <bean id="uk.nonUrgentEmergencyRule" parent="uk.emergencyRule" singleton="false">
    <property name="name" value="Non-urgent Emergency" />
    <property name="description" value="Emergency - non-urgent emergencies" />
    <property name="emergencyNumber" value="101" />
  </bean>

  <!-- properties for all long distance rules:  pstnPrefixOptional, pstnPrefix,
    longDistancePrefixOptional, longDistancePrefix, externalLen, permissionName -->
  <bean id="uk.longDistanceRule" parent="defaultLongDistanceRule" singleton="false">
    <property name="pstnPrefixOptional" value="true" />
    <property name="pstnPrefix" value="9" />
    <property name="longDistancePrefixOptional" value="false" />
    <property name="longDistancePrefix" value="0" />
    <property name="name" value="Long Distance" />
    <property name="description" value="Long distance dialing plan" />
    <property name="areaCodes" value="1,2" />
    <property name="externalLen" value="10" />
    <property name="permissionName" value="LongDistanceDialing" />
  </bean>
  <bean id="uk.locationIndependentRule" parent="uk.longDistanceRule" singleton="false">
    <property name="name" value="Location Independent" />
    <property name="description" value="Location independent telephone numbers" />
    <property name="areaCodes" value="3,55,56" />
  </bean>
  <bean id="uk.premiumRate" parent="uk.longDistanceRule" singleton="false">
    <property name="name" value="Premium Rate" />
    <property name="description" value="Premium rate services" />
    <property name="areaCodes" value="90,91,98" />
    <property name="permissionName" value="900Dialing" />
  </bean>
  <bean id="uk.basicRate" parent="uk.longDistanceRule" singleton="false">
    <property name="name" value="Basic Rate" />
    <property name="description" value="Special services - basic rate" />
    <property name="areaCodes" value="84" />
  </bean>
  <bean id="uk.nationalRate" parent="uk.longDistanceRule" singleton="false">
    <property name="name" value="National Rate" />
    <property name="description" value="Special services - national rate" />
    <property name="areaCodes" value="87" />
  </bean>
  <bean id="uk.tollFreeRule" parent="defaultTollFreeRule" singleton="false">
    <property name="name" value="Toll Free" />
    <property name="description" value="Toll free dialing" />
    <property name="areaCodes" value="80" />
    <property name="permissionName" value="TollFree" />
  </bean>
  <bean id="uk.infolineRule" parent="uk.longDistanceRule" singleton="false">
    <property name="name" value="Information" />
    <property name="description" value="Information services" />
    <property name="longDistancePrefixOptional" value="true" />
    <property name="longDistancePrefix" value="" />
    <property name="areaCodes" value="118" />
    <property name="externalLen" value="6" />
    <property name="permissionName" value="900Dialing" />
  </bean>
  <bean id="uk.mobileRule" parent="uk.longDistanceRule" singleton="false">
    <property name="name" value="Mobile Phones" />
    <property name="description" value="Mobile phone dialing" />
    <property name="areaCodes" value="75,77,78,79" />
    <property name="permissionName" value="Mobile" />
  </bean>
  <bean id="uk.internationalRule" parent="defaultInternationalRule" singleton="false">
    <property name="name" value="International" />
    <property name="description" value="International dialing" />
    <property name="longDistancePrefix" value="00" />
    <property name="externalLen" value="-1" />
    <property name="areaCodes" value="" />
    <property name="permissionName" value="InternationalDialing" />
  </bean>

  <!-- List of default rules provided by the UK dial plan template -->
  <bean id="uk.dialPlan" parent="defaultDialPlan" singleton="false">
    <property name="rules">
      <list>
        <ref bean="uk.voicemailRule" />
        <ref bean="uk.attendantRule" />
        <ref bean="uk.emergencyRule" />
        <ref bean="uk.oldEmergencyRule" />
        <ref bean="uk.nonUrgentEmergencyRule" />
        <ref bean="uk.longDistanceRule" />
        <ref bean="uk.locationIndependentRule" />
        <ref bean="uk.premiumRate" />
        <ref bean="uk.basicRate" />
        <ref bean="uk.nationalRate" />
        <ref bean="uk.tollFreeRule" />
        <ref bean="uk.infolineRule" />
        <ref bean="uk.mobileRule" />
        <ref bean="uk.internationalRule" />
      </list>
    </property>
  </bean>

</beans>

=== SIPfoundry/legacy-sipxecs/sipXconfig/neoconf/test/sipxplugin.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN"
	"http://www.springframework.org/dtd/spring-beans.dtd">
<beans>
  <bean id="testPhoneModel" parent="abstractPhoneModel" class="org.sipfoundry.sipxconfig.phone.TestPhoneModel">
    <property name="label" value="Test Phone" />
  </bean>

  <bean id="testPhone" class="org.sipfoundry.sipxconfig.phone.TestPhone" singleton="false" parent="abstractPhone" />
  
  <bean id="testXmlRpcFunctions" class="org.sipfoundry.sipxconfig.xmlrpc.XmlRpcProxyFactoryBean">
    <property name="serviceUrl">
      <value>http://localhost:9997</value>
    </property>
    <property name="serviceInterface">
      <value>org.sipfoundry.sipxconfig.xmlrpc.TestFunctions</value>
    </property>
  </bean>

  <bean id="systemAuditManager" class="org.sipfoundry.sipxconfig.systemaudit.SystemAuditManagerMock"/>
  <bean id="systemAuditManagerImpl" class="org.sipfoundry.sipxconfig.systemaudit.SystemAuditManagerMock"/>

</beans>

=== SIPfoundry/legacy-sipxecs/sipXconfig/neoconf/etc/region_de/dialrules.beans.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN//EN" "http://www.springframework.org/dtd/spring-beans.dtd">
<beans>

  <!--  The default dial plan for Germany  -->

  <!-- properties: voiceMail, voiceMailPrefix -->
  <bean id="de.voicemailRule" parent="defaultInternalRule" singleton="false">
    <property name="name" value="Anrufbeantworter" />
    <property name="description" value="Wählplan für den Anrufbeantworter" />
    <property name="voiceMail" value="101" />
    <property name="voiceMailPrefix" value="8" />
  </bean>
  <!-- properties: extension, attendantAliases -->
  <bean id="de.attendantRule" parent="defaultAttendantRule" singleton="false">
    <property name="name" value="Automatische Vermittlung" />
    <property name="description" value="Wählplan für die automatische Vermittlung" />
    <property name="extension" value="100" />
    <property name="attendantAliases" value="operator 0" />
  </bean>

  <!-- properties: optionalPrefix, emergencyNumber -->
  <bean id="de.emergencyRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Notrufnummer" />
    <property name="description" value="Notrufnummer für Deutschland" />
    <property name="emergencyNumber" value="112" />
  </bean>
  <bean id="de.policeRule" parent="defaultEmergencyRule" singleton="false">
    <property name="name" value="Polizei" />
    <property name="description" value="Notrufnummer für die Polizei" />
    <property name="emergencyNumber" value="110" />
  </bean>

  <!-- properties for all long distance rules:  pstnPrefixOptional, pstnPrefix,
       longDistancePrefixOptional, longDistancePrefix, externalLen, permissionName -->
  <bean id="de.longDistanceRule" parent="defaultLongDistanceRule" singleton="false">
    <property name="name" value="Ferngespräche" />
    <property name="description" value="Wählplan für Ferngespräche" />
    <property name="longDistancePrefixOptional" value="false" />
    <property name="longDistancePrefix" value="0" />
    <property name="externalLen" value="-1" />
    <property name="areaCodes" value="20,21,22,23,24,30,33,34,35,36,38,40,42,43,45,51,52,61,62,68,69,71,72,89,91,94" />
    <property name="permissionName" value="LongDistanceDialing" />
  </bean>
  <bean id="de.altLongDistanceRule" parent="de.longDistanceRule" singleton="false">
    <property name="name" value="Alternative Betreiber" />
    <property name="description" value="Wählplan für Ferngespräche über alternative Netzbetreiber" />
    <property name="areaCodes" value="10" />
    <property name="permissionName" value="LongDistanceDialing" />
  </bean>
  <bean id="de.premiumRateRule" parent="de.longDistanceRule" singleton="false">
    <property name="name" value="Premium-Dienste" />
    <property name="description" value="Anwahl von Premium Diensten" />
    <property name="areaCodes" value="900" />
    <property name="permissionName" value="900Dialing" />
  </bean>
  <bean id="de.tollFreeRule" parent="defaultTollFreeRule" singleton="false">
    <property name="name" value="Free Phone" />
    <property name="description" value="Entgeltfreie Telefondienste" />
    <property name="areaCodes" value="800" />
    <property name="permissionName" value="TollFree" />
  </bean>
  <bean id="de.personalNumberRule" parent="de.longDistanceRule" singleton="false">
    <property name="name" value="Persönliche Rufnummern" />
    <property name="description" value="Anwahl von individuellen (Vanity) Nummern" />
    <property name="areaCodes" value="700" />
    <property name="permissionName" value="LongDistanceDialing" />
  </bean>
  <bean id="de.internationalRule" parent="defaultInternationalRule" singleton="false">
    <property name="name" value="International" />
    <property name="description" value="Wählen von internationalen Nummern" />
    <property name="longDistancePrefix" value="00" />
    <property name="areaCodes" value="" />
    <property name="externalLen" value="-1" />
    <property name="permissionName" value="InternationalDialing" />
  </bean>
  <bean id="de.carrierInfoRule" parent="de.longDistanceRule" singleton="false">
    <property name="name" value="Anbieteransage" />
    <property name="description" value="Bandansage des aktuellen Pre-Selection-Anbieter" />
    <property name="areaCodes" value="31" />
    <property name="permissionName" value="TollFree" />
  </bean>


  <bean id="de.mobileRule" parent="de.longDistanceRule" singleton="false">
    <property name="name" value="Mobiltelefone" />
    <property name="description" value="Wählen von Mobilteilnehmern" />
    <property name="areaCodes" value="15, 16, 17" />
    <property name="externalLen" value="11" />
    <property name="permissionName" value="Mobile" />
  </bean>

  <bean id="de.infolineRule" parent="de.longDistanceRule" singleton="false">
    <property name="name" value="Auskunftsdienste" />
    <property name="description" value="Informationsdienste, welche keine Vorwahl benötigen" />
    <property name="areaCodes" value="118, 194" />
    <property name="longDistancePrefix" value="" />
    <property name="permissionName" value="900Dialing" />
  </bean>
  <bean id="de.servicesRule" parent="de.longDistanceRule" singleton="false">
    <property name="name" value="Verschiedene Dienste" />
    <property name="description" value="Harmonisierte Dienste von sozialem Wert" />
    <property name="areaCodes" value="116" />
    <property name="externalLen" value="6" />
    <property name="longDistancePrefix" value="" />
  </bean>

  <!-- defaultDialPlan defines the "factory default" structure of your valid plan -->
  <!-- this is the list of rules that admin will see after installation and after -->
  <!-- reverting to default -->
  <bean id="de.dialPlan" parent="defaultDialPlan" singleton="false">
    <property name="rules">
      <list>
        <ref bean="de.voicemailRule" />
        <ref bean="de.attendantRule" />
        <ref bean="de.emergencyRule" />
        <ref bean="de.policeRule" />
        <ref bean="de.longDistanceRule" />
        <ref bean="de.altLongDistanceRule" />
        <ref bean="de.premiumRateRule" />
        <ref bean="de.tollFreeRule" />
        <ref bean="de.personalNumberRule" />
        <ref bean="de.internationalRule" />
        <ref bean="de.carrierInfoRule" />
        <ref bean="de.mobileRule" />
        <ref bean="de.infolineRule" />
        <ref bean="de.servicesRule" />
      </list>
    </property>
  </bean>

</beans>
